### ISSUE TITLE
NameError: name 'rfunc' is not defined

### ISSUE THREAD

**Issue by kerrycobb** [broadinstitute/tensorqtl#193]
I installed tensorqtl with conda using this environment specification in a yaml file:
```yaml
name: tensorqtl
dependencies:
- python=3.11
- r-base
- pip
- pip:
  - numpy
  - pandas
  - pandas-plink
  - Pgenlib>=0.90.1
  - pyarrow
  - qtl
  - rpy2
  - scipy
  - torch
  - tensorqtl
  - jupyter
  ```

When trying to run the `tensorqtl_examples.ipynb` example I run into this error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], line 10
      5 cis_df = cis.map_cis(genotype_df, variant_df, 
      6                      phenotype_df.loc[phenotype_pos_df['chr'] == 'chr18'],
      7                      phenotype_pos_df.loc[phenotype_pos_df['chr'] == 'chr18'],
      8                      covariates_df=covariates_df, seed=123456)
      9 # compute q-values (in practice, this must be run on all genes, not a subset)
---> 10 post.calculate_qvalues(cis_df, fdr=0.05, qvalue_lambda=0.85)

File ~/.miniforge/envs/tensorqtl/lib/python3.11/site-packages/tensorqtl/post.py:36, in calculate_qvalues(res_df, fdr, qvalue_lambda, logger)
     34 if qvalue_lambda is not None:
     35     logger.write(f'  * Calculating q-values with lambda = {qvalue_lambda:.3f}')
---> 36 qval, pi0 = rfunc.qvalue(res_df[pval_col], lambda_qvalue=qvalue_lambda)
     38 res_df['qval'] = qval
     39 logger.write(f'  * Proportion of significant phenotypes (1-pi0): {1-pi0:.2f}')

NameError: name 'rfunc' is not defined
```

Looking at the code I see the use of  `sys.path.insert(1, os.path.dirname(__file__))`. I'm pretty sure `__file__` is not defined for a jupyter notebook and this is generally not considered good practice in distributed python packages. 

Would a pull request making changes to the imports are done to be in line with best practices be accepted?
